feign:
  client:
    config:
      default:
        logger-level: ${HTTP_LOG_LEVEL:BASIC}
        connect-timeout: 105000
        read-timeout: 105000
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      useGzipDecoder: true
pix:
  bacen:
    dict:
      url: ${BACEN_AWS_URL}
  partner: ${PARTNER}
  services:
    baas:
      token-manager:
        url: http://baas-pix-token-manager.ms.qa/pix/token-manager
    jdpi:
      claim:
        url: ${JDPI_CLAIM_URL}
      dict:
        url: ${JDPI_DICT_URL}
      headers:
        host: JDPI${ISPB_CLIENT_ID}${JDPI_ENVIRONMENT}.jdPSTI.rtm
      infraction:
        url: ${JDPI_INFRACTION_URL}

logging:
  level:
    com.picpay.banking: ${FEIGN_CLIENTS_LOG_LEVEL:INFO}