resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
        cancelRunningFuture: true
  ratelimiter:
    instances:
      getEntryByCidRateLimiter:
        limitForPeriod: 3600
        limitRefreshPeriod: 60s
        timeoutDuration: 60s
      listCidSetEventsRateLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 60s
        timeoutDuration: 60s

feign:
  client:
    config:
      default:
        logger-level: BASIC
        connect-timeout: 105000
        read-timeout: 105000
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      useGzipDecoder: true
pix:
  bacen:
    dict:
      url: http://baas-pix-proxy-dict-gateway.ms.qa
      sync:
        lockKey: dict::bacen::sync:active
        lockDuration: 3

logging:
  level:
    com.picpay.banking: INFO
