spring:
    flyway:
        baselineOnMigrate: true
    redis:
        host: ${PICPAY_REDIS_HOST}
        keyTtl: ${PICPAY_REDIS_KEY_TTL}
        port: ${PICPAY_REDIS_PORT}
        timeout: ${PICPAY_REDIS_TIMEOUT}
