spring:
    application:
        name: sync
    profiles:
        active:
            - bacen
            - database

server:
    tomcat:
        threads:
            max: 400
            min-spare: 50

picpay:
    ispb: 22896431
    service.name: ${spring.application.name}
    logging:
        level: ${PICPAY_LOGGING_LEVEL}
        appender: ${PICPAY_LOGGING_APPENDER}

logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta([%t]) %m%n"
#logging.level.org.apache.kafka.clients: OFF

management:
    health:
        diskspace:
            enabled: false
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: prometheus, health
            base-path: '/'
            path-mapping:
                prometheus: 'metrics'