server:
  compression:
    enabled: true

spring:
  cloud:
    stream:
      bindings:
        claim-notifications:
          destination: claim-notifications-topic
          binder: kafka
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  redis:
    enabled: false
