server:
  compression:
    enabled: true

spring:
  cloud:
    stream:
      bindings:
        new-infractions:
          destination: new-infraction-reports
          binder: kafka
    task:
      name: INFRACTION_POLLING
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  redis:
    enabled: false
picpay:
  polling:
    infraction:
      limit: 200
  ispb: 22896431
