spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 908jhuhUih8
        url: jdbc:mysql://baas-dict-db.hmg.banking.local:3306/dict
        username: dict
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
        show-sql: false
    main:
        allow-bean-definition-overriding: true
    redis:
        host: localhost
        keyTtl: 24
        port: 6379
        timeout: 5000