feign:
    client:
        config:
            default:
                logger-level: FULL
    compression:
        request:
            enabled: true
            mime-types: text/xml,application/xml,application/json
            min-request-size: 2048
        response:
            enabled: true
            useGzipDecoder: true
logging:
    level:
        com:
            picpay:
                banking:
                    jdpi:
                        clients: ${FEIGN_CLIENTS_LOG_LEVEL:INFO}
management:
    endpoint:
        health:
            show-details: always
        web:
            exposure:
                include: prometheus, health
    endpoints:
        web:
            base-path: /
            path-mapping:
                prometheus: '''metrics'''
picpay:
    logging:
        appender: CONSOLE
        level: ${PICPAY_LOGGING_LEVEL}
pix:
    bacen:
        dict:
            entries:
                url: ${BACEN_AWS_URL}
    partner: ${PARTNER}
    services:
        baas:
            token-manager:
                url: http://baas-pix-token-manager.ms.qa/pix/token-manager
        jdpi:
            claim:
                url: ${JDPI_CLAIM_URL}
            dict:
                url: ${JDPI_DICT_URL}
            headers:
                host: JDPI${ISPB_CLIENT_ID}${JDPI_ENVIRONMENT}.jdPSTI.rtm
            infraction:
                url: ${JDPI_INFRACTION_URL}
server:
    compression:
        enabled: true
    port: ${LOCAL_PORT:8080}
spring:
    datasource:
        driver-class-name: ${DB_DRIVE_CLASS_NAME}
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USERNAME}
    jpa:
        database: ${DB_TYPE}
        hibernate:
            ddl-auto: none
        show-sql: true
    main:
        allow-bean-definition-overriding: true
    redis:
#        cluster:
#            nodes: ${PICPAY_REDIS_HOSTS}
#            max-redirects: 5
        host: ${PICPAY_REDIS_HOST}
        port: ${PICPAY_REDIS_PORT}
        timeout: ${PICPAY_REDIS_TIMEOUT}
        keyTtl: ${PICPAY_REDIS_KEY_TTL}

