spring:
    application:
        name: dict-sync-cid-file
    cloud:
        task:
            name: sync-cid-file
        config:
            enabled: false
picpay:
    ispb: 22896431
    logging:
        appender: CONSOLE
        level: INFO
