spring:
    application:
        name: dict-sync-cid-file
    cloud:
        task:
            name: SYNC_CID_FILE
        config:
            enabled: false
#   jpa:
#       properties:
#           hibernate:
#               jdbc:
#                   batch_size: 100
#               order_inserts: true
#               order_updates: true
#               generate_statistics: true
picpay:
    ispb: 22896431
    logging:
        appender: CONSOLE
        level: INFO
    dict:
        pixkey:
            notification-dispatcher: true
