spring:
    application:
        name: sync-cid-file
    cloud:
        task:
            name: sync-cid-file
    profiles:
        active:
            - feign
            - database
            - redis
picpay:
    ispb: 22896431
