spring:
    application:
        name: sync-cid-file
    cloud:
        task:
            name: sync-cid-file
    profiles:
        active:
            - bacen
            - database
picpay:
    ispb: 22896431
